[project]
name = "notebooks"
version = "0.1.0"
description = "Lehre Notebooks"
readme = 'README.rst'
requires-python = '>=3.12'
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
